cask "iterm2"
cask "chromium"

brew "zsh"
brew "git"
brew "diff-so-fancy"
brew "tig"
brew "tmux"
brew "reattach-to-user-namespace"
brew "fzf"
brew "make"

brew "neovim"
brew "tree-sitter"
brew "rust"
tap "homebrew/cask-fonts"
cask "font-powerline-symbols"
cask "font-hack"

brew "leiningen"
brew "clojure"
tap "clojure-lsp/brew"
brew "clojure-lsp-native"
tap "borkdude/brew"
brew "clj-kondo"

brew "go"
brew "rbenv"
brew "ruby-build"
brew "pyenv"

tap "sass/sass"
brew "sass"
