#!/bin/bash

# pretty git log by Gary Bernhardt
# https://www.destroyallsoftware.com/screencasts/catalog/pretty-git-logs

HASH="%C(yellow)%h%C(reset)"
RELATIVE_TIME="%Cgreen(%ar)%C(reset)"
AUTHOR="%C(bold blue)<%an>%C(reset)"
REFS="%C(red)%d%C(reset)"
SUBJECT="%s"

FORMAT="$HASH}$RELATIVE_TIME}$AUTHOR}$REFS $SUBJECT"

show_git_head() {
    pretty_git_log -1
    git show -p --pretty="tformat:"
}

pretty_git_log() {
    git log --graph --pretty="tformat:${FORMAT}" $* |
        # Replace (2 years ago) with (2 years)
        sed 's/\(^[^<]*\) ago)/\1)/' |
        # Replace (2 years, 5 months) with (2 years)
        sed 's/\(^[^<]*\), [[:digit:]]+ .*months?)/\1)/' |
        # Line columns up based on } delimiter
        column -s '}' -t |
        # Page only if we need to
        less -FXRS
}
