#!/usr/bin/env bash
# inspired by https://github.com/ThePrimeagen/.dotfiles/blob/master/bin/.local/bin/tmux-sessionizer

if [[ $# -eq 1 ]]; then
  selected=$1
else
  selected=$((echo ~/ ; find ~/code ~/work ~/.config -mindepth 1 -maxdepth 1 -type d) | fzf-tmux -h)
fi

if [[ -z $selected ]]; then
  exit 0
fi

tnew $selected
